{
 "title": "Hyperliquid Node Operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "commit",
    "query": {
     "query": "label_values(hl_software_version_info,commit)"
    }
   },
   {
    "name": "commit_date",
    "label": "Commit date",
    "query": {
     "query": "label_values(hl_software_version_info,date)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MISC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Client Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"background-color: #222; padding: 15px; border-radius: 10px; color: #00FF00; font-size: 24px; font-weight: bold; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <strong>Commit Hash:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit</span><br/>\n  <strong>Date:</strong> <span style=\"font-size: 22px; color: #FFDD44;\">$commit_date</span>\n</div>\n"
   }
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_block_height" }
   ]
  },
  { "title": "CONSENSUS METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Validator Jailed Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "targets": [
    { "expr": "validator_jailed_status" }
   ]
  },
  {
   "title": "Jailed Validators Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(validator_jailed_status)" }
   ]
  },
  {
   "title": "Proposals Per Second (15m basis)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(proposer_count_total[15m])",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  {
   "title": "Validator Proposal Share (4h basis)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (proposer) (increase(proposer_count_total[4h]))\n/\nscalar(sum(increase(proposer_count_total[4h])))\n* 100\n",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  { "title": "BLOCK METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Block Height ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hl_block_height", "legendFormat": "block_height" }
   ]
  },
  {
   "title": "Block Time Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "300 / delta(hl_block_height[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "900 / delta(hl_block_height[15m])",
     "legendFormat": "15m"
    },
    {
     "expr": "3600 / delta(hl_block_height[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "14400 / delta(hl_block_height[4h])",
     "legendFormat": "4h"
    },
    {
     "expr": "43200 / delta(hl_block_height[12h])",
     "legendFormat": "12h"
    },
    {
     "expr": "86400 / delta(hl_block_height[24h])",
     "legendFormat": "24h"
    }
   ]
  },
  {
   "title": "Block Apply Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "hl_apply_duration", "legendFormat": "apply_duration" }
   ]
  }
 ]
}