{
 "title": "Hyperliquid",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_block_height", "legendFormat": "Block Height" }
   ]
  },
  {
   "title": "Latest Block Time [UTC]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_latest_block_time * 1000", "legendFormat": "Block Height" }
   ]
  },
  {
   "title": "Current binary up-to-date status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hl_software_up_to_date", "legendFormat": "Up-to-date_status" }
   ]
  },
  {
   "title": "Latest Client Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    { "expr": "hl_software_version", "legendFormat": "Latest Release" }
   ]
  },
  { "title": "CONSENSUS METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Validator Jailed Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 14 },
   "targets": [
    { "expr": "hl_validator_jailed_status" }
   ]
  },
  {
   "title": "Jailed Validators Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(hl_validator_jailed_status)",
     "legendFormat": "Jailed Validators"
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hl_validator_count", "legendFormat": "Validator Count" }
   ]
  },
  {
   "title": "Validator Jailings Timeseries",
   "type": "timeseries",
   "description": "1 = jailed\n0 = not jailed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hl_validator_jailed_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Proposals Per Second (15m basis)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(hl_proposer_count_total[15m])",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  {
   "title": "Validator Proposal Share (4h basis)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (proposer) (increase(hl_proposer_count_total[4h]))\n/\nscalar(sum(increase(hl_proposer_count_total[4h])))\n* 100\n",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  { "title": "BLOCK METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Block Height ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hl_block_height", "legendFormat": "block_height" }
   ]
  },
  {
   "title": "95th percentile block apply time averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "5m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "15m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[1h])) by (le))",
     "legendFormat": "1h"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[4h])) by (le))",
     "legendFormat": "4h"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[12h])) by (le))",
     "legendFormat": "12h"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hl_apply_duration_seconds_bucket[24h])) by (le))",
     "legendFormat": "24h"
    }
   ]
  },
  {
   "title": "Apply Duration Distribution Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(hl_apply_duration_seconds_bucket[15s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Time Distribution Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(hl_block_time_milliseconds_bucket[15s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}