package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/validaoxyz/hyperliquid-exporter/internal/metrics/metricinventory"
)

const (
	beginMarker = "<!-- BEGIN GENERATED METRIC INVENTORY -->"
	endMarker   = "<!-- END GENERATED METRIC INVENTORY -->"
)

func main() {
	metricsDir := flag.String("metrics-dir", ".", "path to the internal/metrics package")
	writePath := flag.String("write", "", "replace the generated inventory block in this file")
	flag.Parse()

	entries, err := metricinventory.Scan(*metricsDir)
	if err != nil {
		fatal(err)
	}
	generated := render(entries)
	if *writePath == "" {
		_, _ = os.Stdout.Write(generated)
		return
	}
	if err := replaceBlock(*writePath, generated); err != nil {
		fatal(err)
	}
}

func render(entries []metricinventory.Entry) []byte {
	current := make([]metricinventory.Entry, 0, len(entries))
	deprecated := make([]metricinventory.Entry, 0)
	for _, entry := range entries {
		if strings.HasPrefix(entry.Compatibility, "deprecated") {
			deprecated = append(deprecated, entry)
		} else {
			current = append(current, entry)
		}
	}
	sort.Slice(current, func(i, j int) bool { return current[i].Name < current[j].Name })
	sort.Slice(deprecated, func(i, j int) bool { return deprecated[i].Name < deprecated[j].Name })

	var out bytes.Buffer
	fmt.Fprintln(&out, beginMarker)
	fmt.Fprintln(&out, "<!-- Generated by: go generate ./internal/metrics -->")
	fmt.Fprintf(&out, "\n### Current families (%d)\n\n", len(current))
	writeTable(&out, current)
	fmt.Fprintf(&out, "\n### Deprecated compatibility families (%d)\n\n", len(deprecated))
	fmt.Fprintln(&out, "These aliases preserve one transition release and are scheduled for removal in the next major release. Their replacement and semantic limits are in [UPGRADING.md](../UPGRADING.md).")
	fmt.Fprintln(&out)
	writeTable(&out, deprecated)
	fmt.Fprintln(&out, endMarker)
	return out.Bytes()
}

func writeTable(out *bytes.Buffer, entries []metricinventory.Entry) {
	fmt.Fprintln(out, "| Metric | Type | Backend | Labels | Registration | HELP | Source |")
	fmt.Fprintln(out, "|---|---|---|---|---|---|---|")
	for _, entry := range entries {
		labels := "-"
		if len(entry.Labels) > 0 {
			quoted := make([]string, 0, len(entry.Labels))
			for _, label := range entry.Labels {
				quoted = append(quoted, "`"+label+"`")
			}
			labels = strings.Join(quoted, ", ")
		}
		fmt.Fprintf(out, "| `%s` | %s | %s | %s | %s | %s | `%s` |\n",
			entry.Name, title(entry.Kind), entry.Backend, labels, entry.Profile, markdownCell(entry.Help), entry.Source)
	}
}

func title(value string) string {
	if value == "" {
		return value
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "&#124;")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.TrimSpace(value)
}

func replaceBlock(path string, generated []byte) error {
	original, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	begin := bytes.Index(original, []byte(beginMarker))
	end := bytes.Index(original, []byte(endMarker))
	if begin < 0 || end < 0 || end < begin {
		return fmt.Errorf("%s is missing the generated inventory markers", path)
	}
	end += len(endMarker)
	replacement := make([]byte, 0, len(original)+len(generated))
	replacement = append(replacement, original[:begin]...)
	replacement = append(replacement, generated...)
	suffix := bytes.TrimLeft(original[end:], "\r\n")
	if len(suffix) > 0 {
		replacement = append(replacement, '\n')
	}
	replacement = append(replacement, suffix...)

	tmp, err := os.CreateTemp(filepath.Dir(path), ".metricdocs-*.md")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(replacement); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpPath, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
